# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeOGW1uv4F7bWmbHsZQ3XVX3Ih5RxcFf
"""

import streamlit as st
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

#Importamos las librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicacion en Streamlit")