# -*- coding: utf-8 -*-
"""app_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qi1mHYWBD2IXmS7_YJgPro21c-kJkXI7
"""

#importamos las librerias
import streamlit as st
import pandas as pd

!pip install streamlit

#importamos las librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicacion en Streamlit")

#lista de tickers inicial
lista_tickers = ["AAPL", "MSFT", "NVDA"]

#SSelector
ticker=st.selectbox("Elija un ticker", lista_tickers)

#Boton
if st.button("Descargar"):
  data=yf.download(ticker,period="1mo")
  st.dataframe(data)