# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qi1mHYWBD2IXmS7_YJgPro21c-kJkXI7
"""

#importamos las librerias
import streamlit as st
import pandas as pd

!pip install streamlit

#importamos las librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicacion en Streamlit")